### ISSUE TITLE
TableView is taking up full view 

### ISSUE THREAD

**Issue by mbalex99** [davbeck/TURecipientBar#33]
I'm having some trouble where the UITableView is taking up the full screen and it's blocking other user controls.

Shouldn't the tableView be beneath the recipientsBar?

I can't figure out where the proper place to put either constraints or the frame modification?

Any tips?

![img_1635](https://cloud.githubusercontent.com/assets/2183729/9079541/1fe5f0ba-3b00-11e5-9cc6-91da92940283.jpg)

![img_1634](https://cloud.githubusercontent.com/assets/2183729/9079542/1fe6b4c8-3b00-11e5-830b-f52fac54ffe7.jpg)

**Comment by davbeck** [comment]
Without seeing your constraints, I'm not sure what is going on.

By default, when the recipient bar is activated the tableView is added to the `contentsController` view and made to fill the entire view, covering everything like you see here. It's insets are then set so that the content falls below the bar. This is for the typical layout where the bar is more or less at the top of the view (minus any nav bars or what have you). By placing the table view over the entire view, it allows the content to bleed through the transparent navigation bars.

However, you aren't placing the bar at the top, but as a field in a larger view. For this custom layout, you will need to implement `recipientsDisplayController:displaySearchResultsTableView:` from `TURecipientsDisplayDelegate`. When this method is present, the `TURecipientsDisplayController` will let the delegate handle adding the tableView to a view and laying it out. The way I have used this is to place the tableView above another scrollView and scroll the bar to the top when it's focused. ([Video](https://davbeck.s3.amazonaws.com/scroll-example.mov))

**Comment by mbalex99** [comment]
Great! Thank you!

**Comment by gsantome** [comment]
Hello @davbeck , I made exactly what you are saying and everything looks better now on my app... but i'm having a problem... im setting my tableView like hidden = YES... and then inside the delegate method recipientsDisplayController:willShowSearchResultsTableView I'm changing the table view to hidden = NO... but I have not lucky... the table never appear... If by default i set at the begging table view hidden = NO everything works perfect.

Do you have any idea on whats going on?

Thanks!
Gonzalo
